# Generated by Django 2.2 on 2019-04-14 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import letras.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Titulo Noticia')),
                ('lead', models.TextField(blank=True, null=True, verbose_name='Lead Noticia')),
                ('text', models.TextField(verbose_name='Texto Noticia')),
                ('video', models.URLField(blank=True)),
                ('priority', models.PositiveIntegerField(choices=[(1, 'Top 1'), (2, 'Top 2'), (3, 'Normal')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre Seccion')),
                ('is_active', models.BooleanField(default=1, verbose_name='Activa')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=30, verbose_name='Cargo')),
                ('role', models.PositiveIntegerField(blank=True, choices=[(1, 'Administrador'), (2, 'Columnista')], null=True)),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Biografia')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=letras.models.user_directory_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.FileField(upload_to=letras.models.user_directory_path)),
                ('name_picture', models.CharField(blank=True, max_length=500, null=True, verbose_name='Texto Noticia')),
                ('is_principal', models.BooleanField(default=1, verbose_name='Principal')),
                ('footer', models.CharField(blank=True, max_length=500, null=True, verbose_name='Pie de foto')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letras.Notice')),
            ],
        ),
        migrations.AddField(
            model_name='notice',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letras.Section'),
        ),
        migrations.AddField(
            model_name='notice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
