# Generated by Django 2.2 on 2019-04-16 04:18

from django.db import migrations, models
import letras.models


class Migration(migrations.Migration):

    dependencies = [
        ('letras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscriptors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre Sucriptior')),
                ('email', models.CharField(max_length=255, verbose_name='Correo')),
                ('is_active', models.BooleanField(default=1, verbose_name='Activo')),
            ],
        ),
        migrations.AlterField(
            model_name='picture',
            name='route',
            field=models.FileField(upload_to=letras.models.notices_directory_path),
        ),
    ]
