# Generated by Django 2.2 on 2019-04-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
