# Generated by Django 2.2 on 2020-04-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='footer',
            field=models.CharField(blank=True, default='Imagen por: Letras Medio', max_length=500, null=True, verbose_name='Pie de foto'),
        ),
    ]
