# Generated by Django 2.2 on 2019-04-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letras', '0002_section_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='color',
            new_name='color_background',
        ),
        migrations.AddField(
            model_name='section',
            name='color_text',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Color RGB'),
        ),
    ]
