# Generated by Django 2.2 on 2020-04-29 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letras', '0002_auto_20200417_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Sección', 'verbose_name_plural': 'Secciones'},
        ),
    ]
