# Generated by Django 3.1 on 2020-08-24 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letras', '0002_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='positions',
            new_name='position',
        ),
    ]
