# Generated by Django 3.1 on 2020-08-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letras', '0003_auto_20200824_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='headers/')),
            ],
        ),
    ]
