# Generated by Django 3.1 on 2020-08-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letras', '0004_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('phone_number', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=30)),
                ('contact', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Header',
        ),
    ]
