# Generated by Django 2.2 on 2019-04-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letras', '0005_auto_20190420_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre metrica')),
                ('visitors', models.IntegerField(verbose_name='Visitantes')),
            ],
        ),
    ]
