# Generated by Django 2.2 on 2020-04-03 20:32

from django.db import migrations, models
import letras.models


class Migration(migrations.Migration):

    dependencies = [
        ('letras', '0005_auto_20190420_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='route',
            field=models.FileField(upload_to=letras.models.notices_directory_path, verbose_name='Ruta de la imagen'),
        ),
    ]
