# Generated by Django 2.2 on 2020-04-03 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letras', '0006_metrics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suscriptors',
            new_name='Suscriptor',
        ),
        migrations.DeleteModel(
            name='Metrics',
        ),
    ]
