# Generated by Django 3.0.5 on 2020-04-03 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('letras', '0007_auto_20200403_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='picture',
            name='is_principal',
            field=models.BooleanField(default=False, verbose_name='Es Principal'),
        ),
        migrations.AlterField(
            model_name='section',
            name='color_background',
            field=models.CharField(blank=True, help_text='Hexagecimal color.', max_length=10, null=True, verbose_name='Color Fondo'),
        ),
        migrations.AlterField(
            model_name='section',
            name='color_text',
            field=models.CharField(blank=True, help_text='Hexagecimal color.', max_length=10, null=True, verbose_name='Color Letra'),
        ),
    ]
