# Generated by Django 3.0.5 on 2020-04-03 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letras', '0008_auto_20200403_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='letras.Notice'),
        ),
    ]
