# Generated by Django 3.0.5 on 2020-04-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letras', '0009_auto_20200403_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='is_principal',
            field=models.BooleanField(default=True, verbose_name='Es Principal'),
        ),
    ]
