# Generated by Django 2.2 on 2020-04-04 21:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letras', '0010_auto_20200404_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
