# Generated by Django 2.2 on 2020-04-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letras', '0011_auto_20200404_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo de la imagen')),
                ('route', models.FileField(upload_to='img/')),
            ],
        ),
    ]
