# Generated by Django 2.2 on 2020-04-11 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letras', '0014_auto_20200411_0033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Generador de link para Imagen', 'verbose_name_plural': 'Generador de link para Imagen'},
        ),
    ]
