# Generated by Django 2.2 on 2020-04-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letras', '0017_auto_20200414_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='footer',
            field=models.CharField(blank=True, default='Imaegen por: Letras Medio', max_length=500, null=True, verbose_name='Pie de foto'),
        ),
    ]
