# Generated by Django 2.2 on 2020-04-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letras', '0018_auto_20200414_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='picure',
            field=models.FileField(default='img', upload_to='img_podcasts'),
        ),
    ]
