# Generated by Django 2.2 on 2020-04-14 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letras', '0019_podcast_picure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='picure',
            new_name='picture',
        ),
    ]
