# Generated by Django 2.2 on 2020-04-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letras', '0020_auto_20200414_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='columns',
            name='image',
            field=models.ImageField(default='img', upload_to='img_columns'),
        ),
    ]
