# Generated by Django 2.2 on 2020-04-14 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letras', '0022_auto_20200414_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columns',
            name='image',
            field=models.ImageField(default='img', upload_to='img_columns', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='columns',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
