# Generated by Django 2.2 on 2020-04-14 21:10

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letras', '0023_auto_20200414_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='picture',
            field=models.FileField(default='img', upload_to='img_podcasts', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='podcast',
            field=models.FileField(upload_to='podcasts/', verbose_name='Audio Podcast'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
