# Generated by Django 2.2 on 2020-04-14 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letras', '0024_auto_20200414_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='priority',
            field=models.PositiveIntegerField(choices=[(1, 'Top 1'), (2, 'Top 2'), (3, 'Normal')], verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letras.Section', verbose_name='Seccion'),
        ),
    ]
