# Generated by Django 2.2 on 2020-04-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letras', '0025_auto_20200414_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Administrador'), (2, 'Columnista'), (3, 'Podcaster')], null=True),
        ),
    ]
